# Generated by Django 5.1.1 on 2024-10-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytenantinfo',
            old_name='Rent_payment_status',
            new_name='rent_payment_status',
        ),
    ]
