# Generated by Django 5.1.1 on 2024-11-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_rent_payment_status_propertytenantinfo_rent_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagement',
            name='acquired_date',
            field=models.DateField(),
        ),
    ]
