# Generated by Django 5.1.1 on 2024-11-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertymanagement_acquired_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymanagement',
            old_name='property_name',
            new_name='property_owner',
        ),
    ]
